### ISSUE TITLE
Add result of verify(jwt) to req?

### ISSUE THREAD

**Issue by tuckerconnelly** [kandros/micro-jwt-auth#6]
So other middleware can use it? Would be nice to:

```js
(req, res) => {
  doSomethingCoolWithUser(req.jwt.id)
  send(res, 200)
}
```

**Comment by kandros** [comment]
@tuckerconnelly would you consider make a pull request with the change?
Thanks

**Comment by tuckerconnelly** [comment]
Boom https://github.com/kandros/micro-jwt-auth/pull/7
